<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="MDerbala" failures="3" tests="6" name="API Tests" time="5.917" errors="0" timestamp="2025-02-26T02:09:34 EET">
  <testcase classname="tests.CreateUserTest" name="testCreateUser" time="3.685"/>
  <testcase classname="tests.GetUserTest" name="testGetUser" time="0.406"/>
  <testcase classname="tests.UpdateUserTest" name="testUpdateUser" time="0.333"/>
  <testcase classname="tests.GetUserErrorTest" name="testUserNotFound" time="0.311">
    <failure type="java.lang.AssertionError" message="Response body should be empty for 404 expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Response body should be empty for 404 expected [true] but found [false]
at tests.GetUserErrorTest.testUserNotFound(GetUserErrorTest.java:20)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testUserNotFound -->
  <testcase classname="tests.CreateUserErrorTest" name="testInvalidUserCreation" time="0.306">
    <failure type="java.lang.AssertionError" message="1 expectation failed.
Expected status code &amp;lt;400&amp;gt; but was &amp;lt;201&amp;gt;.
">
      <![CDATA[java.lang.AssertionError: 1 expectation failed.
Expected status code <400> but was <201>.

at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:108)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:512)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:696)
at io.restassured.internal.ResponseSpecificationImpl.this$2$validateResponseIfRequired(ResponseSpecificationImpl.groovy)
at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:198)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:62)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:135)
at io.restassured.specification.ResponseSpecification$statusCode$0.callCurrent(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:143)
at io.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:89)
at tests.CreateUserErrorTest.testInvalidUserCreation(CreateUserErrorTest.java:18)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- testInvalidUserCreation -->
  <testcase classname="tests.UpdateUserErrorTest" name="testUpdateNonExistentUser" time="0.288">
    <failure type="java.lang.AssertionError" message="Error message should be present expected object to not be null">
      <![CDATA[java.lang.AssertionError: Error message should be present expected object to not be null
at tests.UpdateUserErrorTest.testUpdateNonExistentUser(UpdateUserErrorTest.java:29)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testUpdateNonExistentUser -->
</testsuite> <!-- API Tests -->
